### ISSUE TITLE
Cant download platform character

### ISSUE THREAD

**Issue by Duroxxigar** [kidscancode/godot_recipes#1]
Was browsing around on the site, turns out that you can't download the zip file at the bottom of the platform character example.

http://kidscancode.org/godot_recipes/2d/platform_character/#conclusion

Just takes you to a 404 page

**Comment by cbscribe** [comment]
GH pages is doing something weird with the d/l links. It works fine when I build locally.

**Comment by cbscribe** [comment]
Fixed.
