### ISSUE TITLE
missing code line and explanation in 4.0's "Your first 2d game" tutorial

### ISSUE THREAD

**Issue by dukemagus** [kidscancode/godot_recipes#125]
https://kidscancode.org/godot_recipes/4.x/games/first_2d/first_2d_05/index.html

for this script to work, you need to add an "Input.is_action_pressed("the_shoot_button")" inside the delta function

[The finished project on github](https://github.com/godotrecipes/classic_shmup/blob/master/ship.gd) has the line, though, so it just needs a a paragraph and a small code block on lesson 5

On a side note, the gif also shows the wrong kind of bullet. whomever recorded it used "Player_charged_beam (16 x 16).png" instead of "Player_beam (16 x 16).png". This doesn't prevent the completion of the tutorial, though.

Here's an alternate gif the author can use:

![Godot_v4 0 2-stable_win64_Yyye7lsAdY](https://user-images.githubusercontent.com/31360383/232262302-837f6100-2606-438d-b6a3-c65136abbe24.gif)

**Comment by cbscribe** [comment]
The tutorial has been updated. Thanks!
