### ISSUE TITLE
Cross and Dot Product in GD4 Math Tutorial

### ISSUE THREAD

**Issue by JBartscher** [kidscancode/godot_recipes#126]
Hi,
it seems that the last two scentences in the tutorial [VECTORS: USING DOT AND CROSS PRODUCT](https://kidscancode.org/godot_recipes/4.x/math/dot_cross_product/index.html) are somewhat switched up. 
The .gif in the tutorial shows us that the dot product can be used to identifiy if something ist left or right and cross product can be used to identify if sth. is in front or behind of something.
So:
````
Dot product: Using the result, we can tell if the object is in front of (> 0) or behind (< 0) us.
Cross product: Using the result, we can tell if the object is to the left (> 0) or right (< 0).
````
should then be:
````
Cross product: Using the result, we can tell if the object is in front of (> 0) or behind (< 0) us.
Dot product: Using the result, we can tell if the object is to the left (> 0) or right (< 0).
````

**Comment by cbscribe** [comment]
The text is correct. If you look at the animation:

* The red arrow is our forward direction. The green arrow is the direction vector pointing to some other object.

* When the green arrow is pointing to the right, the two arrows are more aligned, and the dot product is positive - the object is in front of us.
* When the green arrow is pointing to the left, dot product is negative - the object is behind us.
And so on.
