### ISSUE TITLE
Step 09 : shield_changed signal not connected

### ISSUE THREAD

**Issue by AlexandreBrach** [kidscancode/godot_recipes#130]
In the UI, the shield is not displayed because the `shield_changed` signal from Player scene  is not connected to anything.

To make it works, I have to connect the signal in the main scene that will apply the change in the UI : 

```
func _ready():
  spawn_enemies()
  $Player.shield_changed.connect(update_shield)

func update_shield(max_shield, shield):
  $CanvasLayer/UI.update_shield( max_shield, shield )
```

**Comment by cbscribe** [comment]
It's not necessary to do this at all. The `update_shield()` function is in the UI script already, so adding another function to call it is redundant.

You also don't need to connect the signal in code, you can connect the player's `shield_changed` signal directly to the `update_shield` function in the UI using the editor. I am adding some clarifying text to that effect in the tutorial.
