### ISSUE TITLE
[Discussion] Know Your Nodes: Path2D and PathFollow2D

### ISSUE THREAD

**Issue by cbscribe** [kidscancode/godot_recipes#94]
Discussion for http://godotrecipes/kyn/path2d/

**Comment by belzecue** [comment]
`offset and unit_offset - these properties represent the distance along the path relative to the beginning. offset is measured in pixels while unit_offset is a percentage (eg 0 is the start, .05 is halfway, 1.0 is the end)
`

Since when is 0.05 halfway to 1.0?? :)

**Comment by cbscribe** [comment]
Fixed :)
