### ISSUE TITLE
Hooking Up Reinforcement learning

### ISSUE THREAD

**Issue by WSPluta** [kidscancode/godot_recipes#95]
Hope you are well.

I was wondering if you ever considered to running this project with reinforcement learning use case. 
Similar to this https://learn.unity.com/course/ml-agents-hummingbirds

**Comment by cbscribe** [comment]
I can't say I have. That article looks interesting, but it builds on what looks like a pretty comprehensive ML plugin for Unity. I wonder if anyone is working on something similar for Godot.
